name: LUV
favicon: null
layout_spectrum: 1
typography_spectrum: 0.414
title: luscious universal visualization
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f0'
    - '#c3c6ca'
    - '#8e9090'
    - '#54534f'
    - '#2b2219'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
