name: LUV
favicon: null
layout_spectrum: 0
typography_spectrum: 0.414
title: luscious universal visualization
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf9fa'
    - '#48474c'
    - '#797983'
    - '#010005'
    - '#a5a1a2'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
